### ISSUE TITLE
node-npm 执行出错

### ISSUE THREAD

**Issue by jesset** [coolsnowwolf/packages#19]
npm -h 执行即报错，不能安装任何包

```
# npm -h
Error: Cannot convert name to ASCII
    at Url.parse (url.js:337:23)
    at Object.urlParse [as parse] (url.js:97:13)
    at Object.validateUrl [as validate] (/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:172:13)
    at validate (/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:221:24)
    at validate (/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:187:11)
    at /usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:104:12
    at Array.map (<anonymous>)
    at /usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:70:15
    at Array.forEach (<anonymous>)
    at Function.clean (/usr/lib/node_modules/npm/node_modules/nopt/lib/nopt.js:58:21)
/usr/lib/node_modules/npm/lib/npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/lib/node_modules/npm/lib/npm.js:61:13)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
```

包信息：
```

# opkg info node
Package: node
Version: v8.16.1-1
Depends: libc, libssp, librt, libpthread, libstdcpp, libopenssl, zlib, libnghttp2, libuv, libhttp-parser, icu
Status: install ok installed
Section: lang
Architecture: x86_64
Size: 5390516
Filename: node_v8.16.1-1_x86_64.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses
 an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js'
 package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
Installed-Time: 1579241783


# opkg info node-npm
Package: node-npm
Version: v8.16.1-1
Depends: libc, libssp, librt, libpthread, node
Status: install user installed
Section: lang
Architecture: x86_64
Size: 3785191
Filename: node-npm_v8.16.1-1_x86_64.ipk
Description: NPM is the package manager for NodeJS
Installed-Time: 1579241784

```

**Comment by jesset** [comment]
禁用icu 库后临时解决 （--with-intl=none)
